import type { Metadata } from "next";
import { Arsenal_SC, Merienda, Rethink_Sans } from "next/font/google";
import "./globals.css";
import InitialLoader from "@/components/ui/initial-loader";

const rethinkSans = Rethink_Sans({
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const arsenalSC = Arsenal_SC({
  variable: "--font-arsenal-sc",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const merienda = Merienda({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-merienda",
});

export const metadata: Metadata = {
  title: "Acalme o seu coração",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth transition-all">
      <body
        className={`${rethinkSans.className} ${arsenalSC.variable} ${merienda.variable} antialiased scroll-smooth`}
      >
        <InitialLoader />
        {children}
      </body>
    </html>
  );
}
